version: '3.6'

services:
 mssql:
  image: mcr.microsoft.com/mssql/server:2019-latest
  container_name: mssql
  restart: always
  ports:
   - "1433:1433"
  environment:
   SA_PASSWORD: "!Ab123456"
   ACCEPT_EULA: "Y"
   MSSQL_PID: "Express"
   MSSQL_DATA_DIR: /var/opt/mssql/data
   MSSQL_LOG_DIR: /var/opt/mssql/log
   MSSQL_BACKUP_DIR: /var/opt/mssql/bak
  volumes:
   - ./docker/db/data:/var/opt/mssql/data
   - ./docker/db/log:/var/opt/mssql/log
   - ./docker/db/bak:/var/opt/mssql/bak